nginx:
  image: tutum/nginx
  ports:
    - "8080:80"
  volumes:
    - ./etc/nginx/sites-available/default:/etc/nginx/sites-available/default
    - ./etc/nginx/sites-available/default:/etc/nginx/sites-enabled/default

    - ./etc/nginx/logs/nginx-error.log:/var/log/nginx/error.log
    - ./etc/nginx/logs/nginx-access.log:/var/log/nginx/access.log

phpfpm:
  build: ./etc/php
  ports:
    - "9000:9000"
  volumes:
    - ./public_html:/var/www

mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}